### ISSUE TITLE
Possible .PAK Mod Release?

### ISSUE THREAD

**Issue by b3ck** [CactusPie/Palworld-DisableBuildingRestrictions#1]
Is there any way you could make this a .PAK mod that I can add into my:

`PalServer\Pal\Content\Paks\~mods` folder on my dedicated server?

**Comment by CactusPie** [comment]
I'm not sure if it is possible to make it as a .PAK, as I've never worked with it, but if it is possible, it require a complete rewrite, so I'm not planning to do it, sorry

**Comment by b3ck** [comment]
Okay no worries, just thought I would ask =)


Take Care,
-b3ck
